### ISSUE TITLE
Logical Name Mapper: Redirecting a non-existent channel should give a runtime error

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess#10]
If the <targetChannel> value is out of range, no error is given but uninitialised values seems to be accessed.

**Comment by phako** [comment]
Isn't that fixed with fdc138dea6fd3fe0461f843b7b4b62faa2261718 ?

**Comment by killenb** [comment]
Yes, it is already fixed. It seems it was missed because the fix is not released yet. I think I checked with the latest release and forgot to check the master. Plus it was forgotten to close the ticket.
