### ISSUE TITLE
Move ExceptionDummy to DeviceAccess

### ISSUE THREAD

**Issue by nshehz** [ChimeraTK/DeviceAccess#103]
Follow up ticket for [#97 ](url)
- Move ExceptionDummy from ApplicationCore to DeviceAccess.
- Don't forget to move the tests.
- Check if all the test works in ApplicationCore.

**Comment by vargheseg** [comment]
e3ea41b0d0c2c6136b3acba6b48220b5bd322d0e should close this ticket
