### ISSUE TITLE
isfunctional() implementation for LogicalNameMapper.

### ISSUE THREAD

**Issue by nshehz** [ChimeraTK/DeviceAccess#107]
Check if LogicalNameMapper needs a custom implementation of isFunctional().
Todo: add more details to the ticket.

**Comment by killenb** [comment]
The backend shoudl check isFunctional() of all its target backend and only report true if all targets are working.

**Comment by vargheseg** [comment]
Changes commited in ecdf136501f891d7c506d6dba4314543bb87c880
