### ISSUE TITLE
Test throwing in postRead/postWrite

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#118]
This is a follow-up for ticket #117 
Child of ChimeraTK/ApplicationCore#123

* Identify all tests that have brohasSeenExceptionken in DeviceAccess and fix them
* Check the logical test coverage and check what needs to be tested to fulfill the ApplictionCore ExceptionHandling and InitialValuePropagation Spec
* Check which servers and applications that directly use DeviceAcces have failed (except for ApplicationCore and all of its dependencies)

Adapting ApplicationCore and the ExceptionHandlingDecorator is a separate ticket,

**Comment by mhier** [comment]
Done as part of the systematic tests
