### ISSUE TITLE
Issues with TransferElement::activeFuture

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess#124]
The logic around TransferElement::activeFuture is flawed, when looking at it at a wider scope. It is used to prevent that multiple calls to readAsync() need to re-generate the future even if it has not yet been fulfilled. On the other hand, the TransferFuture is designed to be reused anyway, hence backends will need/want to create the future exactly once in the lifetime of the accessor. Creating a new future involves memory allocation which anyway should be avoided.

Maybe readAsync() (and hence readTransferAsync()/doReadTransferAsync()) should return instead a reference to the TransferFuture which is created by the accessor implementation once.

**Comment by killenb** [comment]
Has become obsolete with the new spec. The TransferFuture will be removed.
