### ISSUE TITLE
Remove unncessary defaults for arguments of implementation functions in TransferElement

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess#130]
Functions like writeTransfer() or doWriteTransfer() currently have an argument versionNumber with a default value. This default value is unneeded, because it is never called by the user and the value for that argument is only passed through from the corresponding public API function, e.g. write() (which of course needs to keep the default value for its argument).

These redundant default values affect the risk of implementation errors by not passing on the value properly.

Identify and remove those redundant default values. If this results in errors, because some code relies on these, closely check the failing code. Even if it is correct, it might be better to place the value directly where used instead of keeping the default value. This needs to be checked from case to case (if there are any legit cases).

**Comment by killenb** [comment]
In the current master only write() and writeDestructively() have the default argument for the version number. All internal function require the argument to be passed.
