### ISSUE TITLE
TransferElement Spec: Check that logic_errors are thrown when they should

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#149]
According to C.5, logic errors must be thrown if certain logical inconsistencies are detected.

Especially the scenario that a device changes its behaviour (PVs which were writable become read only, PCs no longer exist) must first throw a runtime_error, and after the device has been re-opened detect the inconsistency and throw a logic error (Spec. 5.3)

Also #148 is part of this ticket

**Comment by mhier** [comment]
Done as apart of the UnifiedBackendTest
