### ISSUE TITLE
Improve tests for TransferGroup exception handling

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#157]
The current test only is checking ChimeraTK::runtime_error in two separate transfers.

To be tested:
* errors in preRead()
* boost::numeric::bad_numeric_cast in postRead()
* The combination of boost::thread_interrupted and other exception when reading
* errors in copy decorators (if this makes sense, don't exactly understand what they are doing
* all tests for exception handling when writing.

**Comment by mhier** [comment]
Systematic tests along the TransferGroup spec is done
