### ISSUE TITLE
Write tests for Device::setException

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#159]
Probably part of the generic backend test

**Comment by mhier** [comment]
The current assumption should be that everything stated in the TE specification is either tested by the TransferElement base class test or by the UnifiedBackendTest.

**Comment by killenb** [comment]
How does the unified backend test check that all accessor implementations in the LNM Backend do it correctly?

**Comment by mhier** [comment]
Generally, the UnifiedBackendTest is provided with a list of accessors which all are tested (actually multiple lists, to separate registers by capabilities, like sync and async readable and writeable registers). We of course have to make sure that all implementations are covered by these lists.

**Comment by killenb** [comment]
ah, ok. sounds good.

**Comment by mhier** [comment]
done as part of the UnifiedBackendTest
