### ISSUE TITLE
DMapFilesParser::parse_one_directory fails with all dmap files that do not have a valid map file for an entry

### ISSUE THREAD

**Issue by phako** [ChimeraTK/DeviceAccess#17]
which means it properly only works with old-style pcie device lines. Old-style doocs backend lines that have "none" as the map file will make it fail as well as new-style dmap files where the map file is passed to the back-end using a parameter

**Comment by vargheseg** [comment]
Closing this one; we decided remove DMapFilesParser. Think only the command line tools use this and https://github.com/ChimeraTK/CommandLineTools/issues/3 should remove it there as well.
