### ISSUE TITLE
ASAN test on Jenkis is failing

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#170]
The asan job is reporting several failing tests:
The following tests FAILED:
	  3 - testSharedDummyBackend (Failed)
	  8 - testLMapTypeHintModifierPlugin (Failed)
	 10 - testDummyBackend (Failed)
	 25 - testLMapBackend (Failed)
	 28 - testLMapMathPlugin (Failed)
	 38 - testLMapForceReadOnlyPlugin (Failed)
	 39 - testLMapBackendUnified (Failed)
	 40 - testLMapMonostableTriggerPlugin (Failed)
	 48 - testLMapFile (Failed)

Most of them are memory leaks in the LMAP, but there are also issues from the undefined behaviour sanitizer, most probably uninitialised variables.

**Comment by mhier** [comment]
all tests are now passing at least on Ubuntu 16.04
