### ISSUE TITLE
Logical Name Mapper: Tests for double buffer plugin

### ISSUE THREAD

**Issue by ckampm** [ChimeraTK/DeviceAccess#184]
Write tests for the double buffer plugin implemented in #30. See that issue for specification and firmware interface,

Definition of done:
- [ ] Tests with different register types and with and without TransferGroup

**Comment by mhier** [comment]
Tests should be done with the unified backend test. Testing with and without TransferGroup should then be unnecessary.

**Comment by jhktimm** [comment]
See branch for progress wip/jhktimm/#184

**Comment by jhktimm** [comment]
See follow up ticket #189
