### ISSUE TITLE
Logical Name Mapper: Tests for double buffer plugin - follow up for #30 and #184

### ISSUE THREAD

**Issue by jhktimm** [ChimeraTK/DeviceAccess#189]
In branch origin/wip/doubleBuffering_plugin_with_tests
you will find a merge of wip/jhktimm/#184 an unfinished test based on the unified backend test (ticket #184) and
brach origin/wip/varghese/issue_30_doubleBuffering_plugin the implementation of the double buffer (ticket #30).

DONE:

- implementation of the double buffer
- doubleBuffer.xlmap with the syntax of the double buffer plugin
- DoubleBuffer.map dummy (that would have to be revised)
- implementation and test call back function for read in dummy backend

TODO:
- DoubleBuffer.map check if the register are ok with all the values.
- In testDoubleBufferng, open the register in a correct way.
At the moment the test fails with:

> 
> ExceptionDummy::BackendRegisterer: registering backend type ExceptionDummy
> Running 1 test case...
> === UnifiedBackendTest for (logicalNameMap?map=doubleBuffer.xlmap&target=(ExceptionDummy?map=DoubleBuffer.map))
> unknown location(0): fatal error in "testUnified": memory access violation at address: 0x000001d8: no mapping at fault address
> 
> *** 1 failure detected in test suite "SubdeviceBackendUnifiedTest"

- Use call back function for read from dummy backend, to see if the flags are set.

**Comment by mhier** [comment]
This ticket is now tracked in Redmin #7983, but due to the amount of information here we keep it open and refer to it from Redmine.
