### ISSUE TITLE
Config for Makefiles is not working in tumbeweed

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#24]
`ChimeraTK-DeviceAccess-config --ldflags` reports flag as -l-lpthread (instead of just -lpthread). This only shows on tumbleweed and only in the config generated for Makefiles, not in the FindXXX.cmake file.

**Comment by mhier** [comment]
fixed in the project-template, see commit 134a381685160ecd58f45d3ca527d5fa9bee51fd

**Comment by mhier** [comment]
Apparent problem in EPICS-IOC-Adapter not yet solved, presumably project-template needs to be merged in all dependencies...

**Comment by mhier** [comment]
After merging the changes of project-template to all relevant projects the problem no longer appears.
