### ISSUE TITLE
Plugin loading and binary incompatibility - part 1

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess#27]
Background:

The current plugin loading mechanism in the backend factory requires binary compatibility of all shared libraries used by the plugin with all currently loaded shared libraries. There are two distinct scenarios to address:
- The version of DeviceAccess used to compile the plugin is incompatible with the one used to compile the application
- The version of any other library used by both the plugin and the application or another plugin are incompatible.

This ticket tries to address the second scenario. A separate ticket will be made for the first.

What to do:
Currently, dlopen() is used to load the plugin. Instead dlmopen() shall be used to load the plugin into its own namespace (also called link-map list).

How to do it:
See this example:
https://github.com/mhier/segregatedLinkingExample

Definition of complete:
- [ ] Implementation
- [ ] Manual test and briefly document in this ticket how the manual test was done. (I think an automated test is too complicated.) Rough idea: use something like libA/libB of the example above, hack an existing application and an existing backend plugin to use them, then make sure it does the right thing.
- [ ] Ask the ticket master to select #28 for the board

**Comment by nshehz** [comment]
We used libraries from https://github.com/mhier/segregatedLinkingExample (by Martin Hierholzer),
where LibA and LibB are binary incompatible and LibB depends on LibC.
- Linked DoocsBackend against LibA.
- Linked QtHardMon against LibC.
- Used QtHardMon to open a doocsBackend. 
 
Loaded DoocsBackend in DeviceAccess using **dlopen** and noticed that the function called from within the DoocsBackend to LibA was not correct. (It called LibC function).

Loaded DoocsBackend in DeviceAccess using **dlmopen** and noticed that the function called from within the DoocsBackend to LibA was correct.

**Comment by mhier** [comment]
#38 is the pull request for this ticket. Review and bug fixing in progress.

**Comment by mhier** [comment]
New tickets will be created for this issue.
