### ISSUE TITLE
Race condition in rebot test

### ISSUE THREAD

**Issue by phako** [ChimeraTK/DeviceAccess#36]
./testRebotHeartbeatCount 
Running 1 test case...
function TestIMPL:: returning now = 0
function TestIMPL:: returning now = 0
function TestIMPL:: returning now = 0
test locked manually , mayget is true
unknown location(0): fatal error: in "RebotHeartbeatCountTestSuite/testHeartbeat1": signal: generated by kill() (or family); uid=0; pid=0
/home/jens/DeviceAccess/tests/executables_src/testRebotHeartbeatCount.cpp(37): last checkpoint
terminating with uncaught exception of type ChimeraTK::logic_error: Device has not been opened correctly

It seems the open() call finishes sometimes faster than the rebot test server updating its variables

**Comment by killenb** [comment]
This issue is not reproducible any more. Neither Jenkins has seen it lately nor can I see it with 'stress' and running the test in a loop.
Hence I close this ticket.
