### ISSUE TITLE
Support IEEE single-precision floating point registers in mapfile, NumericAddressBackend

### ISSUE THREAD

**Issue by vargheseg** [ChimeraTK/DeviceAccess#7]
Registers with data interpreted as floating point may be useful to have. Current implementation of the NumericAddressBackend assumes firmware will always want data from device access in fixed point representations.

There can be use cases where floating point support simplifies application code on the firmware side; a case where this is specially applicable is when data from these registers have to be forwarded to micro controller code on hardware.

**Comment by killenb** [comment]
Released in 01.01.00 (4d3ea08)
