### ISSUE TITLE
Write a type changing plugin for the logical name mapping

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#89]
If one variable needs to be connected to different types in ApplicationCore, you have to be able to convert the data type in the logical name mapping when placing the copies of the variable for automatic connection.
In addition this plugin can be used to convert an int to a double before being used in the multiply plugin (which would be only a hack because there would be an addition variable flying around)

**Comment by killenb** [comment]
Will probably use the TypeChangingDecorator, which is supposed to be moved from the control system adapter (see #44).

**Comment by mhier** [comment]
The typeHintModifier plugin should cover all use cases.
