### ISSUE TITLE
COPY_FAKE_DEVICE_REF_FILE target causes problems on macOS

### ISSUE THREAD

**Issue by smarsching** [ChimeraTK/DeviceAccess#95]
When trying to build the lastest version of DeviceAccess on macOS (10.14.6) I got an error message that "tests/._Reference_Device" could not be copied from the source tree.

The rule that tries to copy this file is defined in `tests/CMakeLists.txt`:

```
ADD_CUSTOM_TARGET(COPY_FAKE_DEVICE_REF_FILE ALL
       COMMAND ${CMAKE_COMMAND} -E
      copy  ${CMAKE_SOURCE_DIR}/tests/._Reference_Device ${PROJECT_BINARY_DIR}/tests/._Reference_Device
      VERBATIM
  )
```

The reference file did in fact not exist in my source tree, because it had not been created by `git pull`. I had to explicitly create it using `git checkout tests/._Reference_Device` and after doing this the build completed.

My guess is that because files starting with `._` usually have a special meaning on macOS, `git pull` does not create such files. For this reason, I suggest renaming this file because I cannot eliminate the possibility that using such a special file name has other inadvertent side effects on macOS.

**Comment by killenb** [comment]
I agree that we should not use such special names. If I see it correctly it is a leftover from some legacy dummy that does not exist any more. It has just not been cleaned up. I will verify it and remove this.
