### ISSUE TITLE
Implement isFunctional() in Rebot Backend

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#98]
This ticket is directly connected to #97 (remove default implementation of isFunctional()).

The Rebot backend needs an implementation that tells if the backend is working as intended. Please check, but I think it can simply return whether the `connection` is open. If a read or write fails, the connection is closed, as well as on a timeout on the heartbeat. Hence the `connection` object is the correct indicator that the backend is functional.

dod
* [x] Extend the timeout tests and check that isFunctional() is reporting true and false correctly when it should
* [x] Also extend the test (or write a new one if it does not exist yet) which tests the heartbeat.

**Comment by jhktimm** [comment]
see branch issue98
